version: '3'
services:
  flask:
    build: ./app
    volumes:
      - ./app:/server
    depends_on:
      - db

  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask